question_data = [
    {"category": "Entertainment: Video Games",
     "type": "boolean",
     "difficulty": "easy",
     "question": "The Indie Game Development Studio Cing, developers of Hotel Dusk and Last Window, went bankrupt on March 1st, 2010.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]
     },
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "hard",
     "question": "What device allows Tracer to manipulate her own time in the game &quot;Overwatch&quot;?",
     "correct_answer": "Chronal Accelerator",
     "incorrect_answers": ["B.L.I.N.K", "Spacial Displacement Manipulator", "TMD (Time Manipulation Device)"]},
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "easy",
     "question": "What was the original name of Crash Bandicoot?", "correct_answer": "Willie Wombat",
     "incorrect_answers": ["Coco Bandicoot", "Marvelous Mole", "Wally Wombat"]},
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "hard",
     "question": "In Monster Hunter Generations, which of these hunter arts are exclusive to the Longsword?",
     "correct_answer": "Unhinged Spirit", "incorrect_answers": ["Shoryugeki", "Provoke", "Demon Riot"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
     "question": "In &quot;Call Of Duty: World At War&quot;, the first appearance of the &quot;PPSH-41&quot; in &quot;Zombies&quot; was in the map &quot;Der Riese&quot;.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "question": "The ghosts in &quot;Pac-Man&quot; and &quot;Ms. Pac-Man&quot; have completely different behavior.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
     "question": "Several characters in &quot;Super Mario 64&quot; blink their eyes, including Mario himself.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "medium",
     "question": "In the game Tom Clancy&#039;s Rainbow 6 Siege, what organization is Valkyrie from?",
     "correct_answer": "Navy Seals", "incorrect_answers": ["S.A.S", "G.I.G.N", "F.B.I"]},
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "medium",
     "question": "The &#039;64&#039; in the Nintendo-64 console refers to what?",
     "correct_answer": "The bits in the CPU architecture",
     "incorrect_answers": ["The number of megabytes of RAM", "Capacity of the ROM Cartridges in megabytes",
                           "Clock speed of the CPU in Hertz"]},
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "easy",
     "question": "In the video game, Half-life, what event started the Half-life universe as we know today?",
     "correct_answer": "The Resonance Cascade",
     "incorrect_answers": ["World War 3", "The Xen Attack", "The Black Mesa Nuke"]}]
